### ISSUE TITLE
Emptiness of geometry objects

### ISSUE THREAD

**Issue by domire8** [aica-technology/control-libraries#90]
This is something I definitely hoped to avoid but here we are. The `Shape` and `Ellipsoid` classes have not been part of our refactors lately and now it seems we have to give it a minimum amount of attention anyway. In particular, we need to define what an *empty* shape is. I don't want to go in detail here because we don't use those classes frequently and the 7.0 release is already enough work.

The problem with emptiness of shapes is that they have several attributes that could be empty itself. The 'center state' of a shape is a Cartesian state, for instance.

My propositions (and outcome of discussions in person):
- The center state of a Shape can never be empty. This is achieved by constructing it as identity state and not allowing empty state in the setter
- Upon construction of a shape or any derived class, all attributes are constructed with a sensible default value. The object itself however, stays empty until one of these attributes is explicitly set
- Add an `Identity` constructor that is the same as the empty constructor, but marked as filled.

My goal here is to make as few changes as possible while enabling similar behavior with the rest of the library such that we can finish other issues like timestamp management and throwing an exception if the state is empty.

@eeberhard @buschbapti

**Comment by eeberhard** [comment]
Thanks, as we discussed, I think points 1 and 2 are valid.

I'm not sure of the real utility of a "default" static constructor (point 3) beyond making some test cases a bit less verbose, since you would want to set the values for any reasonable application. I would almost prefer to leave it out, but as long as it is clear and tidy then I don't mind it.

`Identity` is clear in the context of matrices / transformation matrix, `Zero` is self-explanatory, but `Default` is a bit vague. `Ellipsoid::Unit()` might be the most unambiguous.

**Comment by buschbapti** [comment]
Thanks `Unit` is much better. I think it could make sense to have those constructors.
